#!/bin/sh
# Copyright (C) 2015 OpenWrt.org
# Copyright (C) 2016 Yousong Zhou <yszhou4tech@gmail.com>

. /lib/functions/uci-defaults.sh

board_config_update

ucidef_set_board_id "khadas,edge"
ucidef_set_model_name "Khadas Edge"

board_config_flush

exit 0
