#!/bin/sh

# runs after 10-wifi-detect created /etc/config/wireless entries
[ "${ACTION}" = "add" ] || exit 0
[ -x /usr/sbin/wifi-autoconf ] || exit 0

/usr/sbin/wifi-autoconf && /sbin/wifi reload >/dev/null 2>&1
exit 0
