#!/bin/sh

## hyphop ##

#= post install base

PR=$(dirname $0)

. $PR/build.conf
. $PR/build.lib

pkg=$PR/pkg

echo "[i] install packages ($PKG_MGR)">&2

$pkg update || FAIL "$PKG_MGR update"

## firewall
case $FIREWALL in
    fw3)
    echo "[i] firewall: fw3 (iptables)">&2
    case $PKG_MGR in
	apk)
	# replace firewall4 by firewall (fw3) in one transaction
	$pkg install firewall iptables-zz-legacy '!firewall4' || FAIL firewall
	;;
	*)
	$pkg remove --force-depends firewall4
	$pkg install firewall iptables-zz-legacy || FAIL firewall
	;;
    esac
    ;;
    *)
    echo "[i] firewall: fw4 (nftables)">&2
    ;;
esac

# mountd
# avahi-daemon-service-ssh avahi-daemon-service-http \
# blockd

$pkg install rsync bwm-ng curl procps-ng-pkill tcpdump nano mc \
    fdisk sfdisk i2c-tools usbutils evtest netcat aria2 \
    shadow-useradd shadow-userdel shadow-usermod \
    gzip tar unzip unrar coreutils-dd coreutils-stat \
    inotifywatch inotifywait \
    coreutils-stty \
    avahi-dbus-daemon avahi-utils \
    mount-utils dosfstools e2fsprogs resize2fs blkid losetup dtc uboot-envtools \
    comgt luci-proto-3g usb-modeswitch \
    kmod-hid \
    iw wpad-mbedtls wpa-cli \
    wireless-tools iwinfo \
    iperf iperf3 pv \
    ttyd \
    samba4-client cifsmount \
    nfs-utils \
    ppp-mod-pptp luci-proto-ppp \
    ipset libpcre2 \
    wpan-tools wireguard-tools luci-proto-wireguard \
    pciutils \
    libzstd zstd \
    || FAIL "install base packages"

[ "$FIREWALL" = "fw3" ] && {
    $pkg install iptables-mod-tproxy iptables-mod-trace \
    || FAIL "install iptables modules"
}

#    openvpn-mbedtls luci-app-openvpn \
#    luci-app-https-dns-proxy \

exit 0
