#!/bin/sh

## hyphop ##

#= post install servers variant

PR=$(dirname $0)
pkg=$PR/pkg

NAME=${0#*post_install_}

. $PR/build.conf
. $PR/build.lib

echo "[i] add $NAME">&2

$pkg install openssh-client openssh-sftp-server || FAIL
$pkg install luci-app-sqm || FAIL
$pkg install samba4-server luci-app-samba4 || FAIL
$pkg install blockd || FAIL
$pkg install nfs-kernel-server nfs-kernel-server-utils || FAIL
