#!/bin/sh

## hyphop ##

#= wget wrapper -> replace to curl -> for opkg / apk
#=      solver many download problems

# opkg: wget -q -O /tmp/opkg-njnCFe/Packages.gz URL
# apk:  wget -q -T 60 [--no-check-certificate] URL -O -

    [ "$MAXTRY" ] || \
        MAXTRY=21
    [ "$DL_MIN_SPEED" ] || \
        DL_MIN_SPEED=10000
    [ "$DL_MIN_SPEED_TIME" ] || \
        DL_MIN_SPEED_TIME=3

[ "$OPKG_CURL_SILENT" ] && \
    OPKG_CURL_ARGS="-s -S"

# echo "[i] OPKG_CURL_SILENT: $OPKG_CURL_SILENT">&2

OUT=
URL=
TIMEOUT=

while [ $# -gt 0 ]; do
    case "$1" in
	-O) OUT="$2"; shift ;;
	-O*) OUT="${1#-O}" ;;
	-T) TIMEOUT="$2"; shift ;;
	-q) OPKG_CURL_ARGS="-s -S" ;;
	-*) ;;
	*) URL="$1" ;;
    esac
    shift
done

[ "$URL" ] || {
    echo "[e] wget wrapper: url undefined">&2
    exit 1
}

[ "$OUT" ] || OUT="$(basename "$URL")"

RESUME="-C-"
[ "$OUT" = "-" ] && RESUME=

[ "$TIMEOUT" ] && \
    OPKG_CURL_ARGS="$OPKG_CURL_ARGS --connect-timeout $TIMEOUT"

exec curl \
    $RESUME -f \
    -jkL -o"$OUT" "$URL" \
    $OPKG_CURL_ARGS -Y $DL_MIN_SPEED -y $DL_MIN_SPEED_TIME  \
    --retry $MAXTRY --retry-delay 3 \
    --retry-connrefused
